### ISSUE TITLE
Cannot be installed if the application was renamed from "\App" namespace!

### ISSUE THREAD

**Issue by gildniy** [lasallecms/lasallecms-l5-usermanagement-pkg#28]
Hello, the package is designed only for applications having as name "App", can you plz consider some people who renamed their applications to something like "Blabla"? Because the vendor try to search something like "App\Http\Controllers\Controller" intead of "Blabla\Http\Controllers\Controller".

Thanks!

**Comment by bbloom** [comment]
This is the first LaSalle Software comment from the world-at-large. Congrats! I think this is a complaint too -- a complaint I do not understand either. 

This user management package is designed solely for use with my LaSalleCMS. It is not a stand-alone package at all.
